# Example code
Notes: 
- For a new connection, must first follow all steps exactly from [here](https://developers.google.com/sheets/api/quickstart/python#step_1_turn_on_the_api_name).
- The **credentials.json** file should live in the same directory as the notebook; alternatively, specify the full path to the file in the `client.flow_from_clientsecrets` line of code.

### Imports

In [75]:
# Standard
import pandas as pd
import numpy as np

# Google stuff
from apiclient.discovery import build
from httplib2 import Http
from oauth2client import file, client, tools

In [3]:
# Setup the Sheets API; just do this once
SCOPES = 'https://www.googleapis.com/auth/spreadsheets.readonly'
store = file.Storage('token.json')
creds = store.get()

if not creds or creds.invalid:
    flow = client.flow_from_clientsecrets('credentials.json', SCOPES)
    creds = tools.run_flow(flow, store)
service = build('sheets', 'v4', http=creds.authorize(Http()))

### Extract the data and put into a dataframe

Example uses [this sheet](https://docs.google.com/spreadsheets/d/1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgvE2upms/edit#gid=0):

In [76]:
SPREADSHEET_ID_TEST = '1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgvE2upms'
RANGE_NAME_TEST = 'Class Data!A1:F' # start with first row so we capture headers

This could be put into a function:

In [74]:
# capture all the data
result = service.spreadsheets().values().get(spreadsheetId = SPREADSHEET_ID_TEST,
                                         range=RANGE_NAME_TEST).execute()

# column names are in first row
col_names = result['values'][0]
ncols = len(col_names)

# how many rows (excluding header row)?
nrows = len(result['values']) - 1

print('Dataframe will be {} rows by {} columns.'.format(nrows,ncols))

# make an empty dataframe to store data
df = pd.DataFrame(np.zeros((nrows,ncols)))

# fill the data frame
for i in np.arange(nrows):
    this_row = result['values'][i+1]

    for j in np.arange(ncols):
        df.iloc[i,j] = this_row[j]

# add the column names
df.columns = col_names

df

Dataframe will be 30 rows by 6 columns.

,Student Name,Gender,Class Level,Home State,Major,Extracurricular Activity
0,Alexandra,Female,4. Senior,CA,English,Drama Club
1,Andrew,Male,1. Freshman,SD,Math,Lacrosse
2,Anna,Female,1. Freshman,NC,English,Basketball
3,Becky,Female,2. Sophomore,SD,Art,Baseball
4,Benjamin,Male,4. Senior,WI,English,Basketball
5,Carl,Male,3. Junior,MD,Art,Debate
6,Carrie,Female,3. Junior,NE,English,Track & Field
7,Dorothy,Female,4. Senior,MD,Math,Lacrosse
8,Dylan,Male,1. Freshman,MA,Math,Baseball
9,Edward,Male,3. Junior,FL,English,Drama Club
10,Ellen,Female,1. Freshman,WI,Physics,Drama Club
11,Fiona,Female,1. Freshman,MA,Art,Debate
12,John,Male,3. Junior,CA,Physics,Basketball
13,Jonathan,Male,2. Sophomore,SC,Math,Debate
14,Joseph,Male,1. Freshman,AK,English,Drama Club
15,Josephine,Female,1. Freshman,NY,Math,Debate
16,Karen,Female,2. Sophomore,NH,English,Basketball
17,Kevin,Male,2. Sophomore,NE,Physics,Drama Club
18,Lisa,Female,3. Junior,SC,Art,Lacrosse
19,Mary,Female,2. Sophomore,AK,Physics,Track & Field
20,Maureen,Female,1. Freshman,CA,Physics,Basketball
21,Nick,Male,4. Senior,NY,Art,Baseball
22,Olivia,Female,4. Senior,NC,Physics,Track & Field
23,Pamela,Female,3. Junior,RI,Math,Baseball
24,Patrick,Male,1. Freshman,NY,Art,Lacrosse
25,Robert,Male,1. Freshman,CA,English,Track & Field
26,Sean,Male,1. Freshman,NH,Physics,Track & Field
27,Stacy,Female,1. Freshman,NY,Math,Baseball
28,Thomas,Male,2. Sophomore,RI,Art,Lacrosse
29,Will,Male,4. Senior,FL,Math,Debate